ALTER TABLE zones ADD COLUMN boundary_geojson TEXT;
ALTER TABLE zones ADD COLUMN color VARCHAR(7) DEFAULT '#3b82f6';
ALTER TABLE zones ADD COLUMN allowed_roles VARCHAR(255) DEFAULT '';
ALTER TABLE zones ADD COLUMN access_tags VARCHAR(255) DEFAULT '';
